### PR TITLE
Create Random Meal Generator

### PR DESCRIPTION
**Pull request by Kirti-Pant**
The Random Meal Generator is a Python program that randomly selects a complete meal for the day, including an appetizer, main course, and dessert.

How It Works:
1. Predefined Lists: The program includes lists of options for each course, such as Samosa and Paneer Tikka for appetizers, Butter Chicken and Dal Makhani for main courses, and Gulab Jamun and Kheer for desserts.
2. Random Selection: It uses the random.choice() function to select one item from each list.

Output: The selected meal components are displayed clearly. 

This tool simplifies meal planning, encourages variety, and can be easily customized to suit your preferences!

### CODE REVIEW

**Comment by Kirti-Pant** [comment]
@sumanth-0 , I've added my pull request.

**Comment by Kirti-Pant** [comment]
@sumanth-0 please let me know if I've successfully contributed in this issue?

**Comment by sumanth-0** [comment]
Hey @Kirti-Pant looks like ur contributing for hacktoberfest,generally the review time is 7 days by hacktoberfest software,you have contributed today... so if hacktober deems ur pr as accepted within 3 days one of ur pr will be passed

**Comment by Kirti-Pant** [comment]
@sumanth-0 thankyou.

**Pull request merged**
