### PR TITLE
Cryptocurrency Price Tracker

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
# Crypto Price Tracker

A simple Python application built using Tkinter to track the live prices of Bitcoin (BTC) and Ethereum (ETH). The application fetches the current cryptocurrency prices from the CoinGecko API and updates them in real-time.

## Features

- Displays live cryptocurrency prices in USD.
- Shows the price change and percentage change for Bitcoin and Ethereum.
- Updates prices every 10 seconds.

## Code Overview

- **get_crypto_price(crypto_id)**: Function to fetch the current price of the cryptocurrency from the CoinGecko API.
- **update_prices()**: Function that updates the displayed prices and their corresponding changes in the GUI.
- The GUI is created using Tkinter, with a title, frames for each cryptocurrency, and labels for displaying the prices and changes.

## Example Screenshot

image

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
@sumanth-0 please review this and merge 
Thank You

**Comment by yashwanthvarma18** [comment]
@sumanth-0 is this repo offically accepted and part of HacktoberFest'24

**Comment by sumanth-0** [comment]
I mean I have checked the hacktoberfest for my repo and its not considered spam. I have followed all the mainter rules. You have a 5 to 6 day of review period where hacktober will review your PR. So if you give quality code it should get considered for a successful PR in hactoberfest. @yashwanthvarma18

**Comment by yashwanthvarma18** [comment]
@sumanth-0 as of now there are no spam or invalid tags on this right and everthing is fine right

**Comment by sumanth-0** [comment]
Yep i am mostly not accepting too simple projects now for this reason.

**Pull request merged**
